### ISSUE TITLE
Tagged for the Esri Github Website

### ISSUE THREAD

**Issue by jrweakland** [Esri/military-planner-application-csharp#47]
This repo needs to be tagged so that it is visible on the Esri Github website (http://esri.github.io/#Military)

**Comment by csmoore** [comment]
Note - the required tags are present ( [at bottom of the file](https://raw.githubusercontent.com/Esri/military-planner-application-csharp/master/README.md)  ) - but it doesn't show up until the index is run on the github.io pages (this usually happens once per month).

Just for everyone's benefit since this fact is somewhat buried in the release checklist: the required tags are ["ArcGISSolutions"](http://esri.github.io/#ArcGISSolutions) , ["military"](http://esri.github.io/#Military) and/or ["intelligence"](http://esri.github.io/#intelligence)

**Comment by jrweakland** [comment]
@csmoore Thanks for the information.
