### ISSUE TITLE
Arabic version for military symbols

### ISSUE THREAD

**Issue by shantaramkamath** [Esri/military-planner-application-csharp#69]
Hello,

I want to localize the military planner application to Arabic (ar-AE). Is it possible to get Arabic version for military symbols? Meaning category, names of symbols, etc. being displayed in Arabic. If it is possible then please let me know how should I go about it.

Regards,
Sam

**Comment by garys-esri** [comment]
Good question. To my knowledge, the supported symbol specifications--MIL-STD-2525C and NATO APP-6(B)--are only distributed in English. Any translations would be unofficial, and Esri's implementation does not include translations. It would take a massive effort to translate the symbol names, and you would have to then use a custom symbol dictionary file, which is not officially supported.

**Comment by csmoore** [comment]
The source of these tags is a Style file (the "dictionary") so this editing would technically be possible ( as mentioned [here](https://github.com/Esri/military-features-data/tree/master/data/mil2525c#editing-the-symbol-dictionary-file) ) - but modifying the dictionary/style is not officially supported at Runtime 10.X (as @garys-esri mentions above). 

Authoring/modifying/localizing the style/stylx file should be supported in the next version of Runtime(Quartz) - but I've never heard of a style file being localized so you may want to talk to your distributor about this (since they typically handle localization issues) - to see if they have ever localized a style file before and could support this.

@abouffard or @joebayles may be able to speak to how NATO/APP-6 handles localization issues with the standard itself.

**Comment by shantaramkamath** [comment]
Thanks for your reply. Closing this ticket.
